### PR TITLE
Use ionicons-api version provided by bom

### PR DESCRIPTION
**Pull request by NotMyFault**
I'm not aware of any version conflict, but if there's one, a release would resolve it.

### CODE REVIEW

**Comment by NotMyFault** [comment]
Likely needs a release of analysis-pom first, the bom addition is quite recent.

**Comment by uhafner** [comment]
The BOM is currently totally broken for my plugins, no idea what is going on :-( 

https://github.com/jenkinsci/bom/pull/1513

**Comment by NotMyFault** [comment]
> The BOM is currently totally broken for my plugins, no idea what is going on :-(
> 
> [jenkinsci/bom#1513](https://github.com/jenkinsci/bom/pull/1513)

Oh boy, that doesn't look too well. Nobody reported any dependency conflicts with this plugin (yet), so I guess this PR is not much of priority, as opposed to a few pipeline components.

**Comment by uhafner** [comment]
> > The BOM is currently totally broken for my plugins, no idea what is going on :-(
> > [jenkinsci/bom#1513](https://github.com/jenkinsci/bom/pull/1513)
> 
> Oh boy, that doesn't look too well. Nobody reported any dependency conflicts with this plugin (yet), so I guess this PR is not much of priority, as opposed to a few pipeline components.

?? All my plugins do not work with the recent version of BOM anymore 😢 You even tried to fix one by yourself!

**Pull request closed without merging**
